# Generated by Django 4.0.4 on 2022-05-05 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='dog',
        ),
        migrations.AddField(
            model_name='slot',
            name='dog1',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog1', to='walk_a_dog_app.dog'),
        ),
        migrations.AddField(
            model_name='slot',
            name='dog2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog2', to='walk_a_dog_app.dog'),
        ),
        migrations.AddField(
            model_name='slot',
            name='dog3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dog3', to='walk_a_dog_app.dog'),
        ),
        migrations.AddField(
            model_name='walk',
            name='status',
            field=models.CharField(choices=[('nie rozpoczęty', 'nie rozpoczęty'), ('w trakcie', 'w trakcie'), ('zakończony', 'zakończony')], default='nie rozpoczęty', max_length=64),
        ),
        migrations.AlterField(
            model_name='dog',
            name='contraindications',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='dog',
            name='recommendation',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='Gdziechodzil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('walk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='walk_a_dog_app.walk')),
            ],
        ),
    ]
