# Generated by Django 4.0.4 on 2022-05-05 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog_app', '0002_remove_walk_dog_slot_dog1_slot_dog2_slot_dog3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='status',
            field=models.CharField(choices=[(1, 'nie rozpoczęty'), (2, 'w trakcie'), (3, 'zakończony')], default=1, max_length=64),
        ),
    ]
