# Generated by Django 4.0.4 on 2022-05-05 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog_app', '0004_rename_gdziechodzil_route'),
    ]

    operations = [
        migrations.AlterField(
            model_name='walk',
            name='status',
            field=models.CharField(choices=[('nie rozpoczęty', 'nie rozpoczęty'), ('w trakcie', 'w trakcie'), ('zakończony', 'zakończony')], default='nie rozpoczęty', max_length=64),
        ),
    ]
