# Generated by Django 4.0.4 on 2022-05-10 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog_app', '0005_alter_walk_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='walk',
            name='status',
        ),
        migrations.AddField(
            model_name='slot',
            name='status',
            field=models.CharField(choices=[('nie rozpoczęty', 'nie rozpoczęty'), ('w trakcie', 'w trakcie'), ('zakończony', 'zakończony')], default='nie rozpoczęty', max_length=64),
        ),
    ]
