# Generated by Django 4.0.4 on 2022-05-13 17:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('walk_a_dog_app', '0006_remove_walk_status_slot_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientopinion',
            name='data',
        ),
        migrations.AddField(
            model_name='walk',
            name='lat',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='walk',
            name='lng',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clientopinion',
            name='dog',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='walk_a_dog_app.dog'),
        ),
        migrations.AlterField(
            model_name='clientopinion',
            name='points',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Route',
        ),
    ]
