# Generated by Django 4.0.4 on 2022-06-03 20:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('walk_a_dog_app', '0008_dog_is_active_alter_clientopinion_review_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='traineropinion',
            name='type',
            field=models.TextField(default='', max_length=250),
        ),
        migrations.AlterField(
            model_name='traineropinion',
            name='client',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='client2', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='traineropinion',
            name='trainer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trainer2', to=settings.AUTH_USER_MODEL),
        ),
    ]
